- alias: Auto color temperature - trigger on time
  id: '1565175229729'
  trigger:
  - platform: template
    value_template: '{{ states(''sensor.time'') == (states.input_datetime.morning_start_time.attributes.timestamp
      | int | timestamp_custom(''%H:%M'', False)) }}'
  - platform: template
    value_template: '{{ states(''sensor.time'') == (states.input_datetime.early_eve_start_time.attributes.timestamp
      | int | timestamp_custom(''%H:%M'', False)) }}'
  - platform: template
    value_template: '{{ states(''sensor.time'') == (states.input_datetime.night_start_time.attributes.timestamp
      | int | timestamp_custom(''%H:%M'', False)) }}'
  condition: []
  action: []
- alias: Auto color temperature - trigger on turn on
  id: '1565175229731'
  trigger:
  - platform: state
    entity_id: light.wc
    to: 'on'
  - platform: state
    entity_id: light.bureau
    to: 'on'
  - platform: state
    entity_id: light.gang
    to: 'on'
  - platform: state
    entity_id: light.keuken_deurkant
    to: 'on'
  - platform: state
    entity_id: light.keuken_koelkastkant
    to: 'on'
  - platform: state
    entity_id: light.nachtkastje
    to: 'on'
  - platform: state
    entity_id: light.slaapkamer_plafond
    to: 'on'
  action:
  - service: python_script.act_turnon
    data_template:
      trigger: '{{trigger.entity_id}}'
- alias: Wake-me up using bedroom lights
  id: '1565175229733'
  trigger:
  - platform: template
    value_template: '{{ states(''sensor.time'') == (states.input_datetime.wakeup_time.attributes.timestamp
      | int | timestamp_custom(''%H:%M'', False)) }}'
  condition:
  - condition: state
    entity_id: input_boolean.wakeup_enabled
    state: 'on'
  - condition: or
    conditions:
    - condition: state
      entity_id: input_boolean.wakeup_weekend
      state: 'on'
    - condition: time
      weekday:
      - mon
      - tue
      - thu
      - fri
  action:
  - data_template:
      kelvin: 4000
      transition: 300
      entity_id: light.slaapkamer
    service: script.fade_in_ikea_light
- id: '1565175229743'
  alias: WC avond bij aanzetten
  trigger:
  - entity_id: light.wc
    platform: state
    to: 'on'
  condition:
  - after: '19:30'
    before: 06:00
    condition: time
  action:
  - data_template:
      brightness_pct: 2
      entity_id: light.wc
      kelvin: 2200
    service: script.turn_on_ikea_light
- id: '1565175229745'
  alias: Gang avond bij aanzetten
  trigger:
  - entity_id: light.gang
    platform: state
    to: 'on'
  condition:
  - after: '19:30'
    before: 06:00
    condition: time
  action:
  - data_template:
      entity_id: light.gang
      kelvin: 2200
    service: light.turn_on
- id: '1566761402059'
  alias: slaapkamer_plafond_cnot
  trigger: []
  condition:
  - condition: state
    entity_id: light.nachtkastje
    state: 'off'
  action:
  - data:
      entity_id: light.slaapkamer_plafond
    service: light.turn_off
- id: '1566761726209'
  alias: slaapkamer_slecht_bezig
  trigger:
  - entity_id: light.slaapkamer_plafond
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: light.nachtkastje
    state: 'off'
  action:
  - data:
      entity_id: light.slaapkamer_plafond
    service: light.turn_off
- id: '1566763763348'
  alias: Welterusten
  trigger:
  - entity_id: light.slaapkamer
    from: 'on'
    platform: state
    to: 'off'
  condition:
  - after: '22:00'
    before: 05:00
    condition: time
  action:
  - service: light.turn_off
