
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:


# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123


# Text to speech
tts:
  - platform: google_translate
    language: 'nl'

input_boolean :
  wakeup_enabled:
    name: "Lichtwekker"
    #initial: on
    icon: mdi:theme-light-dark
  wakeup_weekend:
    name: "Weekend"
    #initial: off # uncomment to reset the value at restart
    icon: mdi:calendar-blank
  auto_color_enabled:
    name: "Kleurverloop"
    initial: on
    icon: mdi:weather-sunset

input_datetime:
  morning_start_time:
    name: "Ochtend"
    has_time: true
    has_date: false
    #initial: "07:30" # comment to not reset the value at restart
  early_eve_start_time:
    name: "Avond"
    has_time: true
    has_date: false
    #initial: "18:00"
  night_start_time:
    name: "Nacht"
    has_time: true
    has_date: false
    #initial: "20:00"

input_number:
  wakeup_time_transition:
    name: "Min duur"
    icon: mdi:timer-sand-full
    #initial: 15
    min: 5
    max: 60
    step: 5
  morning_start_hour:
    name: "Uur"
    icon: mdi:clock
    #initial: 8
    min: 4
    max: 12
    step: 1
  morning_start_minutes:
    name: "Minuten"
    icon: mdi:clock-outline
    #initial: 0
    min: 0
    max: 55
    step: 5



# Light groups
light:
  - platform: group
    name: slaapkamer
    entities:
      - light.nachtkastje
      - light.slaapkamer_plafond
  - platform: group
    name: woonkamer
    entities:
      - light.bureau
      - light.keuken_deurkant
      - light.keuken_koelkastkant
      - light.hoek_woonkamer
  - platform: group
    name: keuken
    entities:
      - light.keuken_deurkant
      - light.keuken_koelkastkant

scene:
  - name: bedtime
    entities:
      light.gang: off
      light.slaapkamer_plafond: off
      light.nachtkastje:
        state: on
        brightness_pct: 20
      light.wc:
        state: on
        brightness_pct: 2


#lovelace: # uncomment to make UI editable in YAML files for custom cards
#  mode: yaml

python_script:  # python scripts folder

telegram_bot:
  - platform: polling
    api_key: !secret telegram_token
    allowed_chat_ids:
      - !secret my_telegram_id
      - !secret gf_telegram_id
      - !secret home_group_telegram_id

notify:
  - name: teledobbyme
    platform: telegram
    chat_id: !secret my_telegram_id
  - name: teledobbygf
    platform: telegram
    chat_id: !secret gf_telegram_id
  - name: teledobbygroup
    platform: telegram
    chat_id: !secret home_group_telegram_id

group: !include groups.yaml
automation: !include_dir_merge_list automation/
script: !include scripts.yaml
sensor: !include sensors.yaml
