title: FC Raven
resources:
  - url: /local/light-entity-card.js
    type: js
views:
  - path: default_view
    title: Home
    badges:
      - sensor.time
      - sun.sun
      - sensor.lightsalarmtomorrow
    cards:
      - type: custom:light-entity-card
        entity: light.woonkamer
      - type: custom:light-entity-card
        entity: light.slaapkamer
      - type: custom:light-entity-card
        entity: light.slaapkamer_plafond
      - type: entities
        entities:
          - input_boolean.auto_color_enabled
          - input_datetime.morning_start_time
          - input_boolean.wakeup_enabled
          - input_boolean.wakeup_weekend
          - input_datetime.early_eve_start_time
          - input_datetime.night_start_time
        title: "Light times"
        show_header_toggle: true
      - type: weather-forecast
        entity: weather.fc_raven
      - type: custom:light-entity-card
        entity: light.nachtkastje
      - type: custom:light-entity-card
        entity: light.gang
      - type: custom:light-entity-card
        entity: light.badkamer
      - type: custom:light-entity-card
        entity: light.wc
        persist_features: false
      - type: media-control
        entity: media_player.living_room
      - type: custom:light-entity-card
        entity: light.keuken
        persist_features: false
      - type: custom:light-entity-card
        entity: light.bureau
        persist_features: false
